### ISSUE TITLE
Doc / Screencast?

### ISSUE THREAD

**Issue by amrrs** [daliusd/xlsx-generator#1]
Hey @daliusd  Came to this from your HN comment. Would be great if there's a small documentation on how to run this / screencast. I'm new to electron! 

Please think of it when you get some time.

A

**Comment by daliusd** [comment]
Check out releases https://github.com/daliusd/xlsx-generator/releases - there is Windows executable. As well there is simple sample files here https://github.com/daliusd/xlsx-generator/tree/master/samples

That would be easiest way to run it now :smile:

If you are on other OS let me know.

**Comment by amrrs** [comment]
Sorry, I'm on Mac!

**Comment by amrrs** [comment]
Do you also suggest any link to learn `electron` ?

**Comment by daliusd** [comment]
In that case you need to install node, yarn and do `yarn install` in your system. I personally just walked through electron documentation. This seems to be good https://electronjs.org/docs/tutorial/first-app
